### ISSUE TITLE
Critical injection failure  / ModifyConstant conflict.

### ISSUE THREAD

**Issue by Kishku7** [Daxanius/NoMiningCooldown#8]
My thoughts below/after:

`[11:17:45] [Render thread/WARN]:
@ModifyConstant conflict. Skipping nmc.mixins.json:ClientPlayerInteractionManagerMixin from mod nmc->@ModifyConstant::MiningCooldownFix(I)I with priority 1000, already redirected by accurateblockplacement.mixins.json:ClientPlayerInteractionManagerMixin from mod accurateblockplacement->@ModifyConstant::FastBlockBreaking(I)I with priority 1000
[11:17:45] [Render thread/WARN]:
@ModifyConstant conflict. Skipping nmc.mixins.json:ClientPlayerInteractionManagerMixin from mod nmc->@ModifyConstant::MiningCooldownFix(I)I with priority 1000, already redirected by accurateblockplacement.mixins.json:ClientPlayerInteractionManagerMixin from mod accurateblockplacement->@ModifyConstant::FastBlockBreaking(I)I with priority 1000
[11:17:45] [Render thread/ERROR]:
Failed to handle packet class_2678[playerId=1419, hardcore=false, levels=[ResourceKey[minecraft:dimension / minecraft:overworld]], maxPlayers=100, chunkRadius=9, simulationDistance=7, reducedDebugInfo=false, showDeathScreen=true, doLimitedCrafting=false, commonPlayerSpawnInfo=class_8589[dimensionType=Reference{ResourceKey[minecraft:dimension_type / minecraft:overworld]=class_2874[fixedTime=OptionalLong.empty, hasSkyLight=true, hasCeiling=false, ultraWarm=false, natural=true, coordinateScale=1.0, bedWorks=true, respawnAnchorWorks=false, minY=-64, height=384, logicalHeight=384, infiniburn=TagKey[minecraft:block / minecraft:infiniburn_overworld], effectsLocation=minecraft:overworld, ambientLight=0.0, monsterSettings=class_7512[piglinSafe=false, hasRaids=true, monsterSpawnLightTest=[0-7], monsterSpawnBlockLightLimit=0]]}, dimension=ResourceKey[minecraft:dimension / minecraft:overworld], seed=-899067887559746994, gameType=SURVIVAL, previousGameType=CREATIVE, isDebug=false, isFlat=true, lastDeathLocation=Optional.empty, portalCooldown=0, seaLevel=1], enforcesSecureChat=true], disconnecting
java.lang.RuntimeException: Mixin transformation of net.minecraft.client.network.ClientPlayerInteractionManager failed
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.16.9.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.9.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:528) ~[?:?]
at knot//MC/net.minecraft.client.network.ClientPlayNetworkHandler.onGameJoin(ClientPlayNetworkHandler.java:441) ~[client-intermediary.jar:?]
at knot//MC/net.minecraft.network.packet.s2c.play.GameJoinS2CPacket.apply(GameJoinS2CPacket.java:69) ~[client-intermediary.jar:?]
at knot//MC/net.minecraft.network.packet.s2c.play.GameJoinS2CPacket.apply(GameJoinS2CPacket.java:17) ~[client-intermediary.jar:?]
at knot//MC/net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils.java:27) ~[client-intermediary.jar:?]
at knot//MC/net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:164) [client-intermediary.jar:?]
at knot//MC/net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) [client-intermediary.jar:?]
at knot//MC/net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:138) [client-intermediary.jar:?]
at knot//MC/net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:123) [client-intermediary.jar:?]
at knot//MC/net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1296) [client-intermediary.jar:?]
at knot//MC/net.minecraft.client.MinecraftClient.run(MinecraftClient.java:922) [client-intermediary.jar:?]
at knot/net.minecraft.client.main.Main.main(Main.java:267) [client-intermediary.jar:?]
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
at knot/io.gitlab.jfronny.libjf.unsafe.asm.AsmTransformer.transformClassBytes(AsmTransformer.java:75) ~[libjf-unsafe-v0-3.18.3-90422f1b6f819661.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.9.jar:?]
... 18 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method MiningCooldownFix(I)I in nmc.mixins.json:ClientPlayerInteractionManagerMixin from mod nmc failed injection check, (0/1) succeeded. Scanned 0 target(s). Using refmap nmc-refmap.json
at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:531) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1490) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:752) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:330) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
at knot/io.gitlab.jfronny.libjf.unsafe.asm.AsmTransformer.transformClassBytes(AsmTransformer.java:75) ~[libjf-unsafe-v0-3.18.3-90422f1b6f819661.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.9.jar:?]
... 18 more
[11:17:45] [Render thread/WARN]:
Client disconnected with reason: Network Protocol Error`

I can see the conflict is with "Accurate Block Placement: Reborn" as the error doesn't happen when I disable that mod.

Unfortunately, that mod is a must-have. once you play the difference, there is no going back.

Can these two mods be combined, or is there a fix that will make these two mods play nice with each other?

**Comment by Daxanius** [comment]
This is not the fault of NoMiningCooldown. 

Ironically ABP-R implemented a copy or NMCs cooldown mixin (as mentioned [here](https://github.com/hschwar/AccurateBlockPlacement-Reborn/issues/5)). Unfortunately this causes the mods to be incompatible because they do essentially the exact same thing.

On the other side, fortunately they do essentially the exact same thing. You can just use ABP-R without issue.
